enum CHILD_WINDOW_STATE {
  INITIAL = "INITIAL",
  LAUNCHING = "LAUNCHING",
  LAUNCHED = "LAUNCHED",
  POPULATING = "POPULATING",
  POPULATED = "POPULATED",
  ERROR = "ERROR",
}

export default CHILD_WINDOW_STATE;
