enum CHILD_WINDOW_ACTION {
  CHANGE_STATE = "CHANGE_STATE",
  SET_WINDOW = "SET_WINDOW",
  LAUNCH = "LAUNCH",
  POPULATE = "POPULATE",
  CLOSE = "CLOSE",
  RESET = "RESET",
}

export default CHILD_WINDOW_ACTION;
