enum CHILD_WINDOW_ACTION {
  CHANGE_STATE = "CHANGE_STATE",
  SET_V1_WINDOW = "SET_V1_WINDOW",
  SET_V2_WINDOW = "SET_V2_WINDOW",
  LAUNCH = "LAUNCH",
  POPULATE = "POPULATE",
  CLOSE = "CLOSE",
  RESET = "RESET",
}

export default CHILD_WINDOW_ACTION;
